version: '3.8'

services:
  frontend:
    container_name: ${IMAGE_NAME}
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/default.conf
      - ./src:/usr/share/nginx/html/src
      - ./.env:/usr/share/nginx/html/.env
    networks:
      - zuidui

networks:
  zuidui:
    driver: bridge
