name: CI-PRE

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      
jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:  
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: make build
  publish-pre:
    name: Publish to pre environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}         
      - name: Publish to pre environment
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          make publish-image-pre